// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inflation_layer_setting.proto

#ifndef PROTOBUF_inflation_5flayer_5fsetting_2eproto__INCLUDED
#define PROTOBUF_inflation_5flayer_5fsetting_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace or_costmap {
class ParaInflationLayer;
class ParaInflationLayerDefaultTypeInternal;
extern ParaInflationLayerDefaultTypeInternal _ParaInflationLayer_default_instance_;
}  // namespace or_costmap

namespace or_costmap {

namespace protobuf_inflation_5flayer_5fsetting_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_inflation_5flayer_5fsetting_2eproto

// ===================================================================

class ParaInflationLayer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:or_costmap.ParaInflationLayer) */ {
 public:
  ParaInflationLayer();
  virtual ~ParaInflationLayer();

  ParaInflationLayer(const ParaInflationLayer& from);

  inline ParaInflationLayer& operator=(const ParaInflationLayer& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ParaInflationLayer(ParaInflationLayer&& from) noexcept
    : ParaInflationLayer() {
    *this = ::std::move(from);
  }

  inline ParaInflationLayer& operator=(ParaInflationLayer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ParaInflationLayer& default_instance();

  static inline const ParaInflationLayer* internal_default_instance() {
    return reinterpret_cast<const ParaInflationLayer*>(
               &_ParaInflationLayer_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ParaInflationLayer* other);
  friend void swap(ParaInflationLayer& a, ParaInflationLayer& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ParaInflationLayer* New() const PROTOBUF_FINAL { return New(NULL); }

  ParaInflationLayer* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ParaInflationLayer& from);
  void MergeFrom(const ParaInflationLayer& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ParaInflationLayer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double inflation_radius = 1;
  bool has_inflation_radius() const;
  void clear_inflation_radius();
  static const int kInflationRadiusFieldNumber = 1;
  double inflation_radius() const;
  void set_inflation_radius(double value);

  // required double cost_scaling_factor = 2;
  bool has_cost_scaling_factor() const;
  void clear_cost_scaling_factor();
  static const int kCostScalingFactorFieldNumber = 2;
  double cost_scaling_factor() const;
  void set_cost_scaling_factor(double value);

  // @@protoc_insertion_point(class_scope:or_costmap.ParaInflationLayer)
 private:
  void set_has_inflation_radius();
  void clear_has_inflation_radius();
  void set_has_cost_scaling_factor();
  void clear_has_cost_scaling_factor();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double inflation_radius_;
  double cost_scaling_factor_;
  friend struct protobuf_inflation_5flayer_5fsetting_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ParaInflationLayer

// required double inflation_radius = 1;
inline bool ParaInflationLayer::has_inflation_radius() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ParaInflationLayer::set_has_inflation_radius() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ParaInflationLayer::clear_has_inflation_radius() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ParaInflationLayer::clear_inflation_radius() {
  inflation_radius_ = 0;
  clear_has_inflation_radius();
}
inline double ParaInflationLayer::inflation_radius() const {
  // @@protoc_insertion_point(field_get:or_costmap.ParaInflationLayer.inflation_radius)
  return inflation_radius_;
}
inline void ParaInflationLayer::set_inflation_radius(double value) {
  set_has_inflation_radius();
  inflation_radius_ = value;
  // @@protoc_insertion_point(field_set:or_costmap.ParaInflationLayer.inflation_radius)
}

// required double cost_scaling_factor = 2;
inline bool ParaInflationLayer::has_cost_scaling_factor() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ParaInflationLayer::set_has_cost_scaling_factor() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ParaInflationLayer::clear_has_cost_scaling_factor() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ParaInflationLayer::clear_cost_scaling_factor() {
  cost_scaling_factor_ = 0;
  clear_has_cost_scaling_factor();
}
inline double ParaInflationLayer::cost_scaling_factor() const {
  // @@protoc_insertion_point(field_get:or_costmap.ParaInflationLayer.cost_scaling_factor)
  return cost_scaling_factor_;
}
inline void ParaInflationLayer::set_cost_scaling_factor(double value) {
  set_has_cost_scaling_factor();
  cost_scaling_factor_ = value;
  // @@protoc_insertion_point(field_set:or_costmap.ParaInflationLayer.cost_scaling_factor)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace or_costmap

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_inflation_5flayer_5fsetting_2eproto__INCLUDED
