// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: static_layer_setting.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "static_layer_setting.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace or_costmap {
class ParaStaticLayerDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ParaStaticLayer>
     _instance;
} _ParaStaticLayer_default_instance_;

namespace protobuf_static_5flayer_5fsetting_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParaStaticLayer, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParaStaticLayer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParaStaticLayer, first_map_only_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParaStaticLayer, subscribe_to_updates_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParaStaticLayer, track_unknown_space_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParaStaticLayer, use_maximum_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParaStaticLayer, unknown_cost_value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParaStaticLayer, trinary_map_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParaStaticLayer, lethal_threshold_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParaStaticLayer, topic_name_),
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 13, sizeof(ParaStaticLayer)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_ParaStaticLayer_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "static_layer_setting.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _ParaStaticLayer_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_ParaStaticLayer_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\032static_layer_setting.proto\022\nor_costmap"
      "\"\330\001\n\017ParaStaticLayer\022\026\n\016first_map_only\030\001"
      " \002(\010\022\034\n\024subscribe_to_updates\030\002 \002(\010\022\033\n\023tr"
      "ack_unknown_space\030\003 \002(\010\022\023\n\013use_maximum\030\004"
      " \002(\010\022\032\n\022unknown_cost_value\030\005 \002(\005\022\023\n\013trin"
      "ary_map\030\006 \002(\010\022\030\n\020lethal_threshold\030\007 \002(\005\022"
      "\022\n\ntopic_name\030\010 \002(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 259);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "static_layer_setting.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_static_5flayer_5fsetting_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ParaStaticLayer::kFirstMapOnlyFieldNumber;
const int ParaStaticLayer::kSubscribeToUpdatesFieldNumber;
const int ParaStaticLayer::kTrackUnknownSpaceFieldNumber;
const int ParaStaticLayer::kUseMaximumFieldNumber;
const int ParaStaticLayer::kUnknownCostValueFieldNumber;
const int ParaStaticLayer::kTrinaryMapFieldNumber;
const int ParaStaticLayer::kLethalThresholdFieldNumber;
const int ParaStaticLayer::kTopicNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ParaStaticLayer::ParaStaticLayer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_static_5flayer_5fsetting_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:or_costmap.ParaStaticLayer)
}
ParaStaticLayer::ParaStaticLayer(const ParaStaticLayer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  topic_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_topic_name()) {
    topic_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.topic_name_);
  }
  ::memcpy(&first_map_only_, &from.first_map_only_,
    static_cast<size_t>(reinterpret_cast<char*>(&lethal_threshold_) -
    reinterpret_cast<char*>(&first_map_only_)) + sizeof(lethal_threshold_));
  // @@protoc_insertion_point(copy_constructor:or_costmap.ParaStaticLayer)
}

void ParaStaticLayer::SharedCtor() {
  _cached_size_ = 0;
  topic_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&first_map_only_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&lethal_threshold_) -
      reinterpret_cast<char*>(&first_map_only_)) + sizeof(lethal_threshold_));
}

ParaStaticLayer::~ParaStaticLayer() {
  // @@protoc_insertion_point(destructor:or_costmap.ParaStaticLayer)
  SharedDtor();
}

void ParaStaticLayer::SharedDtor() {
  topic_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ParaStaticLayer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ParaStaticLayer::descriptor() {
  protobuf_static_5flayer_5fsetting_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_static_5flayer_5fsetting_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ParaStaticLayer& ParaStaticLayer::default_instance() {
  protobuf_static_5flayer_5fsetting_2eproto::InitDefaults();
  return *internal_default_instance();
}

ParaStaticLayer* ParaStaticLayer::New(::google::protobuf::Arena* arena) const {
  ParaStaticLayer* n = new ParaStaticLayer;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ParaStaticLayer::Clear() {
// @@protoc_insertion_point(message_clear_start:or_costmap.ParaStaticLayer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (has_topic_name()) {
    GOOGLE_DCHECK(!topic_name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*topic_name_.UnsafeRawStringPointer())->clear();
  }
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 254u) {
    ::memset(&first_map_only_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&lethal_threshold_) -
        reinterpret_cast<char*>(&first_map_only_)) + sizeof(lethal_threshold_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ParaStaticLayer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:or_costmap.ParaStaticLayer)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool first_map_only = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_first_map_only();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &first_map_only_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bool subscribe_to_updates = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_subscribe_to_updates();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &subscribe_to_updates_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bool track_unknown_space = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          set_has_track_unknown_space();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &track_unknown_space_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bool use_maximum = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          set_has_use_maximum();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &use_maximum_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 unknown_cost_value = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          set_has_unknown_cost_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &unknown_cost_value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bool trinary_map = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          set_has_trinary_map();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &trinary_map_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 lethal_threshold = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {
          set_has_lethal_threshold();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &lethal_threshold_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string topic_name = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_topic_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->topic_name().data(), static_cast<int>(this->topic_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "or_costmap.ParaStaticLayer.topic_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:or_costmap.ParaStaticLayer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:or_costmap.ParaStaticLayer)
  return false;
#undef DO_
}

void ParaStaticLayer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:or_costmap.ParaStaticLayer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required bool first_map_only = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->first_map_only(), output);
  }

  // required bool subscribe_to_updates = 2;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->subscribe_to_updates(), output);
  }

  // required bool track_unknown_space = 3;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->track_unknown_space(), output);
  }

  // required bool use_maximum = 4;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->use_maximum(), output);
  }

  // required int32 unknown_cost_value = 5;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->unknown_cost_value(), output);
  }

  // required bool trinary_map = 6;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->trinary_map(), output);
  }

  // required int32 lethal_threshold = 7;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->lethal_threshold(), output);
  }

  // required string topic_name = 8;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->topic_name().data(), static_cast<int>(this->topic_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "or_costmap.ParaStaticLayer.topic_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->topic_name(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:or_costmap.ParaStaticLayer)
}

::google::protobuf::uint8* ParaStaticLayer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:or_costmap.ParaStaticLayer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required bool first_map_only = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->first_map_only(), target);
  }

  // required bool subscribe_to_updates = 2;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->subscribe_to_updates(), target);
  }

  // required bool track_unknown_space = 3;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->track_unknown_space(), target);
  }

  // required bool use_maximum = 4;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->use_maximum(), target);
  }

  // required int32 unknown_cost_value = 5;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->unknown_cost_value(), target);
  }

  // required bool trinary_map = 6;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->trinary_map(), target);
  }

  // required int32 lethal_threshold = 7;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->lethal_threshold(), target);
  }

  // required string topic_name = 8;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->topic_name().data(), static_cast<int>(this->topic_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "or_costmap.ParaStaticLayer.topic_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->topic_name(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:or_costmap.ParaStaticLayer)
  return target;
}

size_t ParaStaticLayer::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:or_costmap.ParaStaticLayer)
  size_t total_size = 0;

  if (has_topic_name()) {
    // required string topic_name = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->topic_name());
  }

  if (has_first_map_only()) {
    // required bool first_map_only = 1;
    total_size += 1 + 1;
  }

  if (has_subscribe_to_updates()) {
    // required bool subscribe_to_updates = 2;
    total_size += 1 + 1;
  }

  if (has_track_unknown_space()) {
    // required bool track_unknown_space = 3;
    total_size += 1 + 1;
  }

  if (has_use_maximum()) {
    // required bool use_maximum = 4;
    total_size += 1 + 1;
  }

  if (has_unknown_cost_value()) {
    // required int32 unknown_cost_value = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->unknown_cost_value());
  }

  if (has_trinary_map()) {
    // required bool trinary_map = 6;
    total_size += 1 + 1;
  }

  if (has_lethal_threshold()) {
    // required int32 lethal_threshold = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->lethal_threshold());
  }

  return total_size;
}
size_t ParaStaticLayer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:or_costmap.ParaStaticLayer)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x000000ff) ^ 0x000000ff) == 0) {  // All required fields are present.
    // required string topic_name = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->topic_name());

    // required bool first_map_only = 1;
    total_size += 1 + 1;

    // required bool subscribe_to_updates = 2;
    total_size += 1 + 1;

    // required bool track_unknown_space = 3;
    total_size += 1 + 1;

    // required bool use_maximum = 4;
    total_size += 1 + 1;

    // required int32 unknown_cost_value = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->unknown_cost_value());

    // required bool trinary_map = 6;
    total_size += 1 + 1;

    // required int32 lethal_threshold = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->lethal_threshold());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ParaStaticLayer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:or_costmap.ParaStaticLayer)
  GOOGLE_DCHECK_NE(&from, this);
  const ParaStaticLayer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ParaStaticLayer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:or_costmap.ParaStaticLayer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:or_costmap.ParaStaticLayer)
    MergeFrom(*source);
  }
}

void ParaStaticLayer::MergeFrom(const ParaStaticLayer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:or_costmap.ParaStaticLayer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_topic_name();
      topic_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.topic_name_);
    }
    if (cached_has_bits & 0x00000002u) {
      first_map_only_ = from.first_map_only_;
    }
    if (cached_has_bits & 0x00000004u) {
      subscribe_to_updates_ = from.subscribe_to_updates_;
    }
    if (cached_has_bits & 0x00000008u) {
      track_unknown_space_ = from.track_unknown_space_;
    }
    if (cached_has_bits & 0x00000010u) {
      use_maximum_ = from.use_maximum_;
    }
    if (cached_has_bits & 0x00000020u) {
      unknown_cost_value_ = from.unknown_cost_value_;
    }
    if (cached_has_bits & 0x00000040u) {
      trinary_map_ = from.trinary_map_;
    }
    if (cached_has_bits & 0x00000080u) {
      lethal_threshold_ = from.lethal_threshold_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ParaStaticLayer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:or_costmap.ParaStaticLayer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParaStaticLayer::CopyFrom(const ParaStaticLayer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:or_costmap.ParaStaticLayer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParaStaticLayer::IsInitialized() const {
  if ((_has_bits_[0] & 0x000000ff) != 0x000000ff) return false;
  return true;
}

void ParaStaticLayer::Swap(ParaStaticLayer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ParaStaticLayer::InternalSwap(ParaStaticLayer* other) {
  using std::swap;
  topic_name_.Swap(&other->topic_name_);
  swap(first_map_only_, other->first_map_only_);
  swap(subscribe_to_updates_, other->subscribe_to_updates_);
  swap(track_unknown_space_, other->track_unknown_space_);
  swap(use_maximum_, other->use_maximum_);
  swap(unknown_cost_value_, other->unknown_cost_value_);
  swap(trinary_map_, other->trinary_map_);
  swap(lethal_threshold_, other->lethal_threshold_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ParaStaticLayer::GetMetadata() const {
  protobuf_static_5flayer_5fsetting_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_static_5flayer_5fsetting_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ParaStaticLayer

// required bool first_map_only = 1;
bool ParaStaticLayer::has_first_map_only() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void ParaStaticLayer::set_has_first_map_only() {
  _has_bits_[0] |= 0x00000002u;
}
void ParaStaticLayer::clear_has_first_map_only() {
  _has_bits_[0] &= ~0x00000002u;
}
void ParaStaticLayer::clear_first_map_only() {
  first_map_only_ = false;
  clear_has_first_map_only();
}
bool ParaStaticLayer::first_map_only() const {
  // @@protoc_insertion_point(field_get:or_costmap.ParaStaticLayer.first_map_only)
  return first_map_only_;
}
void ParaStaticLayer::set_first_map_only(bool value) {
  set_has_first_map_only();
  first_map_only_ = value;
  // @@protoc_insertion_point(field_set:or_costmap.ParaStaticLayer.first_map_only)
}

// required bool subscribe_to_updates = 2;
bool ParaStaticLayer::has_subscribe_to_updates() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void ParaStaticLayer::set_has_subscribe_to_updates() {
  _has_bits_[0] |= 0x00000004u;
}
void ParaStaticLayer::clear_has_subscribe_to_updates() {
  _has_bits_[0] &= ~0x00000004u;
}
void ParaStaticLayer::clear_subscribe_to_updates() {
  subscribe_to_updates_ = false;
  clear_has_subscribe_to_updates();
}
bool ParaStaticLayer::subscribe_to_updates() const {
  // @@protoc_insertion_point(field_get:or_costmap.ParaStaticLayer.subscribe_to_updates)
  return subscribe_to_updates_;
}
void ParaStaticLayer::set_subscribe_to_updates(bool value) {
  set_has_subscribe_to_updates();
  subscribe_to_updates_ = value;
  // @@protoc_insertion_point(field_set:or_costmap.ParaStaticLayer.subscribe_to_updates)
}

// required bool track_unknown_space = 3;
bool ParaStaticLayer::has_track_unknown_space() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void ParaStaticLayer::set_has_track_unknown_space() {
  _has_bits_[0] |= 0x00000008u;
}
void ParaStaticLayer::clear_has_track_unknown_space() {
  _has_bits_[0] &= ~0x00000008u;
}
void ParaStaticLayer::clear_track_unknown_space() {
  track_unknown_space_ = false;
  clear_has_track_unknown_space();
}
bool ParaStaticLayer::track_unknown_space() const {
  // @@protoc_insertion_point(field_get:or_costmap.ParaStaticLayer.track_unknown_space)
  return track_unknown_space_;
}
void ParaStaticLayer::set_track_unknown_space(bool value) {
  set_has_track_unknown_space();
  track_unknown_space_ = value;
  // @@protoc_insertion_point(field_set:or_costmap.ParaStaticLayer.track_unknown_space)
}

// required bool use_maximum = 4;
bool ParaStaticLayer::has_use_maximum() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void ParaStaticLayer::set_has_use_maximum() {
  _has_bits_[0] |= 0x00000010u;
}
void ParaStaticLayer::clear_has_use_maximum() {
  _has_bits_[0] &= ~0x00000010u;
}
void ParaStaticLayer::clear_use_maximum() {
  use_maximum_ = false;
  clear_has_use_maximum();
}
bool ParaStaticLayer::use_maximum() const {
  // @@protoc_insertion_point(field_get:or_costmap.ParaStaticLayer.use_maximum)
  return use_maximum_;
}
void ParaStaticLayer::set_use_maximum(bool value) {
  set_has_use_maximum();
  use_maximum_ = value;
  // @@protoc_insertion_point(field_set:or_costmap.ParaStaticLayer.use_maximum)
}

// required int32 unknown_cost_value = 5;
bool ParaStaticLayer::has_unknown_cost_value() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void ParaStaticLayer::set_has_unknown_cost_value() {
  _has_bits_[0] |= 0x00000020u;
}
void ParaStaticLayer::clear_has_unknown_cost_value() {
  _has_bits_[0] &= ~0x00000020u;
}
void ParaStaticLayer::clear_unknown_cost_value() {
  unknown_cost_value_ = 0;
  clear_has_unknown_cost_value();
}
::google::protobuf::int32 ParaStaticLayer::unknown_cost_value() const {
  // @@protoc_insertion_point(field_get:or_costmap.ParaStaticLayer.unknown_cost_value)
  return unknown_cost_value_;
}
void ParaStaticLayer::set_unknown_cost_value(::google::protobuf::int32 value) {
  set_has_unknown_cost_value();
  unknown_cost_value_ = value;
  // @@protoc_insertion_point(field_set:or_costmap.ParaStaticLayer.unknown_cost_value)
}

// required bool trinary_map = 6;
bool ParaStaticLayer::has_trinary_map() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void ParaStaticLayer::set_has_trinary_map() {
  _has_bits_[0] |= 0x00000040u;
}
void ParaStaticLayer::clear_has_trinary_map() {
  _has_bits_[0] &= ~0x00000040u;
}
void ParaStaticLayer::clear_trinary_map() {
  trinary_map_ = false;
  clear_has_trinary_map();
}
bool ParaStaticLayer::trinary_map() const {
  // @@protoc_insertion_point(field_get:or_costmap.ParaStaticLayer.trinary_map)
  return trinary_map_;
}
void ParaStaticLayer::set_trinary_map(bool value) {
  set_has_trinary_map();
  trinary_map_ = value;
  // @@protoc_insertion_point(field_set:or_costmap.ParaStaticLayer.trinary_map)
}

// required int32 lethal_threshold = 7;
bool ParaStaticLayer::has_lethal_threshold() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void ParaStaticLayer::set_has_lethal_threshold() {
  _has_bits_[0] |= 0x00000080u;
}
void ParaStaticLayer::clear_has_lethal_threshold() {
  _has_bits_[0] &= ~0x00000080u;
}
void ParaStaticLayer::clear_lethal_threshold() {
  lethal_threshold_ = 0;
  clear_has_lethal_threshold();
}
::google::protobuf::int32 ParaStaticLayer::lethal_threshold() const {
  // @@protoc_insertion_point(field_get:or_costmap.ParaStaticLayer.lethal_threshold)
  return lethal_threshold_;
}
void ParaStaticLayer::set_lethal_threshold(::google::protobuf::int32 value) {
  set_has_lethal_threshold();
  lethal_threshold_ = value;
  // @@protoc_insertion_point(field_set:or_costmap.ParaStaticLayer.lethal_threshold)
}

// required string topic_name = 8;
bool ParaStaticLayer::has_topic_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ParaStaticLayer::set_has_topic_name() {
  _has_bits_[0] |= 0x00000001u;
}
void ParaStaticLayer::clear_has_topic_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void ParaStaticLayer::clear_topic_name() {
  topic_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_topic_name();
}
const ::std::string& ParaStaticLayer::topic_name() const {
  // @@protoc_insertion_point(field_get:or_costmap.ParaStaticLayer.topic_name)
  return topic_name_.GetNoArena();
}
void ParaStaticLayer::set_topic_name(const ::std::string& value) {
  set_has_topic_name();
  topic_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:or_costmap.ParaStaticLayer.topic_name)
}
#if LANG_CXX11
void ParaStaticLayer::set_topic_name(::std::string&& value) {
  set_has_topic_name();
  topic_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:or_costmap.ParaStaticLayer.topic_name)
}
#endif
void ParaStaticLayer::set_topic_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_topic_name();
  topic_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:or_costmap.ParaStaticLayer.topic_name)
}
void ParaStaticLayer::set_topic_name(const char* value, size_t size) {
  set_has_topic_name();
  topic_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:or_costmap.ParaStaticLayer.topic_name)
}
::std::string* ParaStaticLayer::mutable_topic_name() {
  set_has_topic_name();
  // @@protoc_insertion_point(field_mutable:or_costmap.ParaStaticLayer.topic_name)
  return topic_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ParaStaticLayer::release_topic_name() {
  // @@protoc_insertion_point(field_release:or_costmap.ParaStaticLayer.topic_name)
  clear_has_topic_name();
  return topic_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ParaStaticLayer::set_allocated_topic_name(::std::string* topic_name) {
  if (topic_name != NULL) {
    set_has_topic_name();
  } else {
    clear_has_topic_name();
  }
  topic_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), topic_name);
  // @@protoc_insertion_point(field_set_allocated:or_costmap.ParaStaticLayer.topic_name)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace or_costmap

// @@protoc_insertion_point(global_scope)
