// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: local_planner_config.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "local_planner_config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace or_local_planner {
class LocalAlgorithmsDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<LocalAlgorithms>
     _instance;
} _LocalAlgorithms_default_instance_;

namespace protobuf_local_5fplanner_5fconfig_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalAlgorithms, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalAlgorithms, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalAlgorithms, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalAlgorithms, selected_algorithm_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalAlgorithms, frequency_),
  ~0u,
  0,
  1,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(LocalAlgorithms)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_LocalAlgorithms_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "local_planner_config.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _LocalAlgorithms_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_LocalAlgorithms_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\032local_planner_config.proto\022\020or_local_p"
      "lanner\"N\n\017LocalAlgorithms\022\014\n\004name\030\001 \003(\t\022"
      "\032\n\022selected_algorithm\030\002 \001(\t\022\021\n\tfrequency"
      "\030\003 \001(\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 126);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "local_planner_config.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_local_5fplanner_5fconfig_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LocalAlgorithms::kNameFieldNumber;
const int LocalAlgorithms::kSelectedAlgorithmFieldNumber;
const int LocalAlgorithms::kFrequencyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LocalAlgorithms::LocalAlgorithms()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_local_5fplanner_5fconfig_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:or_local_planner.LocalAlgorithms)
}
LocalAlgorithms::LocalAlgorithms(const LocalAlgorithms& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      name_(from.name_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  selected_algorithm_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_selected_algorithm()) {
    selected_algorithm_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.selected_algorithm_);
  }
  frequency_ = from.frequency_;
  // @@protoc_insertion_point(copy_constructor:or_local_planner.LocalAlgorithms)
}

void LocalAlgorithms::SharedCtor() {
  _cached_size_ = 0;
  selected_algorithm_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  frequency_ = 0;
}

LocalAlgorithms::~LocalAlgorithms() {
  // @@protoc_insertion_point(destructor:or_local_planner.LocalAlgorithms)
  SharedDtor();
}

void LocalAlgorithms::SharedDtor() {
  selected_algorithm_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LocalAlgorithms::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LocalAlgorithms::descriptor() {
  protobuf_local_5fplanner_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_local_5fplanner_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LocalAlgorithms& LocalAlgorithms::default_instance() {
  protobuf_local_5fplanner_5fconfig_2eproto::InitDefaults();
  return *internal_default_instance();
}

LocalAlgorithms* LocalAlgorithms::New(::google::protobuf::Arena* arena) const {
  LocalAlgorithms* n = new LocalAlgorithms;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LocalAlgorithms::Clear() {
// @@protoc_insertion_point(message_clear_start:or_local_planner.LocalAlgorithms)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.Clear();
  if (has_selected_algorithm()) {
    GOOGLE_DCHECK(!selected_algorithm_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*selected_algorithm_.UnsafeRawStringPointer())->clear();
  }
  frequency_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool LocalAlgorithms::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:or_local_planner.LocalAlgorithms)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name(this->name_size() - 1).data(),
            static_cast<int>(this->name(this->name_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "or_local_planner.LocalAlgorithms.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string selected_algorithm = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_selected_algorithm()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->selected_algorithm().data(), static_cast<int>(this->selected_algorithm().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "or_local_planner.LocalAlgorithms.selected_algorithm");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double frequency = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {
          set_has_frequency();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &frequency_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:or_local_planner.LocalAlgorithms)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:or_local_planner.LocalAlgorithms)
  return false;
#undef DO_
}

void LocalAlgorithms::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:or_local_planner.LocalAlgorithms)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string name = 1;
  for (int i = 0, n = this->name_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name(i).data(), static_cast<int>(this->name(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "or_local_planner.LocalAlgorithms.name");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(i), output);
  }

  cached_has_bits = _has_bits_[0];
  // optional string selected_algorithm = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->selected_algorithm().data(), static_cast<int>(this->selected_algorithm().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "or_local_planner.LocalAlgorithms.selected_algorithm");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->selected_algorithm(), output);
  }

  // optional double frequency = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->frequency(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:or_local_planner.LocalAlgorithms)
}

::google::protobuf::uint8* LocalAlgorithms::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:or_local_planner.LocalAlgorithms)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string name = 1;
  for (int i = 0, n = this->name_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name(i).data(), static_cast<int>(this->name(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "or_local_planner.LocalAlgorithms.name");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->name(i), target);
  }

  cached_has_bits = _has_bits_[0];
  // optional string selected_algorithm = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->selected_algorithm().data(), static_cast<int>(this->selected_algorithm().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "or_local_planner.LocalAlgorithms.selected_algorithm");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->selected_algorithm(), target);
  }

  // optional double frequency = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->frequency(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:or_local_planner.LocalAlgorithms)
  return target;
}

size_t LocalAlgorithms::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:or_local_planner.LocalAlgorithms)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated string name = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->name_size());
  for (int i = 0, n = this->name_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->name(i));
  }

  if (_has_bits_[0 / 32] & 3u) {
    // optional string selected_algorithm = 2;
    if (has_selected_algorithm()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->selected_algorithm());
    }

    // optional double frequency = 3;
    if (has_frequency()) {
      total_size += 1 + 8;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LocalAlgorithms::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:or_local_planner.LocalAlgorithms)
  GOOGLE_DCHECK_NE(&from, this);
  const LocalAlgorithms* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LocalAlgorithms>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:or_local_planner.LocalAlgorithms)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:or_local_planner.LocalAlgorithms)
    MergeFrom(*source);
  }
}

void LocalAlgorithms::MergeFrom(const LocalAlgorithms& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:or_local_planner.LocalAlgorithms)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  name_.MergeFrom(from.name_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_selected_algorithm();
      selected_algorithm_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.selected_algorithm_);
    }
    if (cached_has_bits & 0x00000002u) {
      frequency_ = from.frequency_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void LocalAlgorithms::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:or_local_planner.LocalAlgorithms)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LocalAlgorithms::CopyFrom(const LocalAlgorithms& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:or_local_planner.LocalAlgorithms)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LocalAlgorithms::IsInitialized() const {
  return true;
}

void LocalAlgorithms::Swap(LocalAlgorithms* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LocalAlgorithms::InternalSwap(LocalAlgorithms* other) {
  using std::swap;
  name_.InternalSwap(&other->name_);
  selected_algorithm_.Swap(&other->selected_algorithm_);
  swap(frequency_, other->frequency_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LocalAlgorithms::GetMetadata() const {
  protobuf_local_5fplanner_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_local_5fplanner_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LocalAlgorithms

// repeated string name = 1;
int LocalAlgorithms::name_size() const {
  return name_.size();
}
void LocalAlgorithms::clear_name() {
  name_.Clear();
}
const ::std::string& LocalAlgorithms::name(int index) const {
  // @@protoc_insertion_point(field_get:or_local_planner.LocalAlgorithms.name)
  return name_.Get(index);
}
::std::string* LocalAlgorithms::mutable_name(int index) {
  // @@protoc_insertion_point(field_mutable:or_local_planner.LocalAlgorithms.name)
  return name_.Mutable(index);
}
void LocalAlgorithms::set_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:or_local_planner.LocalAlgorithms.name)
  name_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void LocalAlgorithms::set_name(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:or_local_planner.LocalAlgorithms.name)
  name_.Mutable(index)->assign(std::move(value));
}
#endif
void LocalAlgorithms::set_name(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:or_local_planner.LocalAlgorithms.name)
}
void LocalAlgorithms::set_name(int index, const char* value, size_t size) {
  name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:or_local_planner.LocalAlgorithms.name)
}
::std::string* LocalAlgorithms::add_name() {
  // @@protoc_insertion_point(field_add_mutable:or_local_planner.LocalAlgorithms.name)
  return name_.Add();
}
void LocalAlgorithms::add_name(const ::std::string& value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:or_local_planner.LocalAlgorithms.name)
}
#if LANG_CXX11
void LocalAlgorithms::add_name(::std::string&& value) {
  name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:or_local_planner.LocalAlgorithms.name)
}
#endif
void LocalAlgorithms::add_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:or_local_planner.LocalAlgorithms.name)
}
void LocalAlgorithms::add_name(const char* value, size_t size) {
  name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:or_local_planner.LocalAlgorithms.name)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
LocalAlgorithms::name() const {
  // @@protoc_insertion_point(field_list:or_local_planner.LocalAlgorithms.name)
  return name_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
LocalAlgorithms::mutable_name() {
  // @@protoc_insertion_point(field_mutable_list:or_local_planner.LocalAlgorithms.name)
  return &name_;
}

// optional string selected_algorithm = 2;
bool LocalAlgorithms::has_selected_algorithm() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void LocalAlgorithms::set_has_selected_algorithm() {
  _has_bits_[0] |= 0x00000001u;
}
void LocalAlgorithms::clear_has_selected_algorithm() {
  _has_bits_[0] &= ~0x00000001u;
}
void LocalAlgorithms::clear_selected_algorithm() {
  selected_algorithm_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_selected_algorithm();
}
const ::std::string& LocalAlgorithms::selected_algorithm() const {
  // @@protoc_insertion_point(field_get:or_local_planner.LocalAlgorithms.selected_algorithm)
  return selected_algorithm_.GetNoArena();
}
void LocalAlgorithms::set_selected_algorithm(const ::std::string& value) {
  set_has_selected_algorithm();
  selected_algorithm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:or_local_planner.LocalAlgorithms.selected_algorithm)
}
#if LANG_CXX11
void LocalAlgorithms::set_selected_algorithm(::std::string&& value) {
  set_has_selected_algorithm();
  selected_algorithm_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:or_local_planner.LocalAlgorithms.selected_algorithm)
}
#endif
void LocalAlgorithms::set_selected_algorithm(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_selected_algorithm();
  selected_algorithm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:or_local_planner.LocalAlgorithms.selected_algorithm)
}
void LocalAlgorithms::set_selected_algorithm(const char* value, size_t size) {
  set_has_selected_algorithm();
  selected_algorithm_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:or_local_planner.LocalAlgorithms.selected_algorithm)
}
::std::string* LocalAlgorithms::mutable_selected_algorithm() {
  set_has_selected_algorithm();
  // @@protoc_insertion_point(field_mutable:or_local_planner.LocalAlgorithms.selected_algorithm)
  return selected_algorithm_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LocalAlgorithms::release_selected_algorithm() {
  // @@protoc_insertion_point(field_release:or_local_planner.LocalAlgorithms.selected_algorithm)
  clear_has_selected_algorithm();
  return selected_algorithm_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LocalAlgorithms::set_allocated_selected_algorithm(::std::string* selected_algorithm) {
  if (selected_algorithm != NULL) {
    set_has_selected_algorithm();
  } else {
    clear_has_selected_algorithm();
  }
  selected_algorithm_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), selected_algorithm);
  // @@protoc_insertion_point(field_set_allocated:or_local_planner.LocalAlgorithms.selected_algorithm)
}

// optional double frequency = 3;
bool LocalAlgorithms::has_frequency() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void LocalAlgorithms::set_has_frequency() {
  _has_bits_[0] |= 0x00000002u;
}
void LocalAlgorithms::clear_has_frequency() {
  _has_bits_[0] &= ~0x00000002u;
}
void LocalAlgorithms::clear_frequency() {
  frequency_ = 0;
  clear_has_frequency();
}
double LocalAlgorithms::frequency() const {
  // @@protoc_insertion_point(field_get:or_local_planner.LocalAlgorithms.frequency)
  return frequency_;
}
void LocalAlgorithms::set_frequency(double value) {
  set_has_frequency();
  frequency_ = value;
  // @@protoc_insertion_point(field_set:or_local_planner.LocalAlgorithms.frequency)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace or_local_planner

// @@protoc_insertion_point(global_scope)
