or_slam:
  pure_localization: false
  use_sim: true
  odom_frame_id: "odom"
  base_frame_id: "base_link"
  global_frame_id: "map"
  laser_topic_name: "scan"
  trunk_topic_name: "trunk_obs"
  transform_tolerance: 0.1

  initial_pose_x: 2.5 #2.5
  initial_pose_y: 8 #8
  initial_pose_a: 0
  initial_cov_xx: 0.1
  initial_cov_yy: 0.1
  initial_cov_aa: 0.1 #0.03 mapping

  sim_sensor_odom:
    alpha1: 0.03
    alpha2: 0.08
    alpha3: 0.08
    alpha4: 0.01
#    alpha1: 0.1
#    alpha2: 0.1
#    alpha3: 0.1
#    alpha4: 0.01

